name: Shiurim
options:
  bundleIdPrefix: com.yoniwillner
  deploymentTarget:
    iOS: "17.0"
targets:
  Shiurim:
    type: application
    platform: iOS
    sources:
      - path: Shiurim
        excludes:
          - Info.plist
    resources:
      - path: ../shared/recordings.json
    info:
      path: Shiurim/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yoniwillner.shiurim
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
